FROM node:lts-iron

WORKDIR /jamiu-imam_fadlullah_ui_garden_build_checks/

COPY public/ /jamiu-imam_fadlullah_ui_garden_build_checks/public
COPY src/ /jamiu-imam_fadlullah_ui_garden_build_checks/src
COPY package.json /jamiu-imam_fadlullah_ui_garden_build_checks/
COPY . /jamiu-imam_fadlullah_ui_garden_build_checks

RUN npm install

CMD ["npm", "run", "storybook"]

