import "./App.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import HomeSection from "./sections/HomeSection";
import AboutSection from "./sections/AboutSection";
import ContactSection from "./sections/ContactSection";
import SkillsSection from "./sections/SkillsSection";
import ProjectsSection from "./sections/ProjectsSection";

function App() {
  const headerLinks = [
    { label: "Home", url: "#home" },
    { label: "About", url: "#about" },
    { label: "Projects", url: "#projects" },
    { label: "Skills", url: "#skills" },
    { label: "Contact", url: "#contact" },
  ];

  const footerLinks = [
    { label: "Twitter", url: "https://twitter.com", disabled: false },
    { label: "GitHub", url: "https://github.com", disabled: false },
    { label: "LinkedIn", url: "https://linkedin.com", disabled: false },
  ];

  const homeSocialLinks = [
    { icon: "twitter", url: "https://twitter.com" },
    { icon: "github", url: "https://github.com" },
    { icon: "linkedin", url: "https://linkedin.com" },
  ];

  const contactInfo = {
    image: "https://via.placeholder.com/300",
    name: "Fadlullah Jamiu-Imam",
    position: "Web Developer",
    description:
      "I am a full-stack developer with a passion for creating beautiful and functional web applications.",
    phone: "123-456-7890",
    email: "john.doe@example.com",
    socialLinks: [
      { icon: "twitter", url: "https://twitter.com" },
      { icon: "github", url: "https://github.com" },
      { icon: "linkedin", url: "https://linkedin.com" },
    ],
  };

  const skills = [
    { name: "React", image: "./images/react.png" },
    {
      name: "HTML",
      image: "./images/html.png",
    },
    { name: "CSS", image: "./images/css.jpg" },
    {
      name: "JavaScript",
      image: "./images/js.png",
    },
    { name: "Ruby", image: "./images/ruby.jpeg" },
    { name: "PHP", image: "./images/php.png" },
    { name: "Java", image: "./images/java.png" },
    {
      name: "PostgreSQL",
      image: "./images/postgresql.png",
    },
    { name: "Git", image: "./images/git.png" },
    { name: "GithHub", image: "./images/github.jpg" },
  ];

  const projects = [
    {
      title: "Zaytoon E-commerce",
      description:
        "Rails Intro Project Goal The goal of my project is to develop a Ruby on Rails application utilizing data generated by the Faker gem. The data will be generated programmatically to simulate real-world scenarios.",
      image: "./images/zaytoon1.png",
      link: "https://github.com/phadhiil001/zaytoon_ecommerce.git",
      disabled: false,
    },
    {
      title: "Art City CMS",
      description:
        "Art City CMS repository! A dynamic CMS tailored specifically for Art City Inc., a vibrant hub for artistic expression nestled in the heart of Winnipeg. Intuitive user interfaces with robust backend functionality. Features that empower administrators, to effortlessly manage content, events, workshops, and artist profiles, for visitors.",
      image: "./images/artcity.png",
      link: "https://github.com/phadhiil001/Art_City_CMS.git",
      disabled: false,
    },
    {
      title: "First Portfolio",
      description: "Description of Project Three",
      image: "./images/first.png",
      link: "https://fadlullah.netlify.app/",
      disabled: false,
    },
  ];

  return (
    <>
      <Header links={headerLinks} />
      <HomeSection
        title="👋 Hey there, I'm "
        subtitle="Front-End Developer"
        description="Welcome to my creative corner! I'm Fadlullah Jamiu-Imam, a passionate front-end developer with two years of experience crafting digital experiences that are both visually stunning and user-friendly."
        socialLinks={homeSocialLinks}
        profileImage="./images/home1.png"
      />
      <AboutSection
        title="About Me"
        description=""
        cvLabel="Download CV"
        cvLink="./images/FSWD.pdf"
        profileImage="./images/about.jpg"
      />
      <ProjectsSection
        title="Projects"
        projects={projects}
      />
      <SkillsSection
        title="Skills"
        skills={skills}
      />
      <ContactSection
        title="Contact Me"
        contactInfo={contactInfo}
      />
      <Footer links={footerLinks} />
    </>
  );
}

export default App;
